export class Book{
    constructor(public bookId:number,public title:String,public author:String,public bookCondition:number,public available:boolean,public returnDate:number){}
}

//{"bookId":70,"title":"TestBook1","author":"TestAuthor1","bookCondition":1,"available":true,"returnDate":0}// Generated by https://quicktype.io


